name: waytolearn
description: "Una aplicaciÃ³n Flutter para aprender de manera interactiva."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase dependencies (actualizadas para Flutter 3.35)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  
  
  # State Management
  provider: ^6.1.1
  
  # Google Sign In (v2 embedding-only)
  google_sign_in: ^7.1.1
  
  # UI & Animation
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  
  # Utils
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env